# Site base configuration
auto: true
source: ./source
plugins: ./source/_plugins
destination: ./web
permalink: /blog/:title.html

# Special markdown plugin to use GitHub flavord syntax highlighting and fenced code blocks
markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

# Site-wide parameters
production_url: http://mywebsite.com
title: GoJekyll !
desc: Welcome to my GoJekyll ! website

# Customization parameters
show_title: true
show_home_link: true

# Use 'exclude' configuration to exclude specific files or folders
# exclude: sass, config.rb